import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { basicFixture, createPgTestServer } from "./pg-helper.mjs";
import { cleanupAssets } from "../mock/media-assets.mjs";

const png = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/lYkAAAAASUVORK5CYII=", "base64");
test("private image upload, MIME validation and 24-hour orphan cleanup", async t => {
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), "admin-assets-"));
  t.after(() => fs.rm(directory, { recursive: true, force: true }));
  const api = await createPgTestServer(t, basicFixture(), { ASSET_DIR: directory });
  const login = await fetch(`${api.base}/auth/login`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ username: "admin", password: "admin123" }) });
  const token = (await login.json()).token;
  const unauthorized = await fetch(`${api.base}/assets`, { method: "POST", headers: { "Content-Type": "image/png" }, body: png });
  assert.equal(unauthorized.status, 401);
  const invalid = await fetch(`${api.base}/assets`, { method: "POST", headers: { "Content-Type": "image/jpeg", Authorization: `Bearer ${token}` }, body: png });
  assert.equal(invalid.status, 415);
  const upload = await fetch(`${api.base}/assets`, { method: "POST", headers: { "Content-Type": "image/png", Authorization: `Bearer ${token}` }, body: png });
  assert.equal(upload.status, 201);
  const { id, url } = await upload.json();
  assert.equal((await fetch(`http://127.0.0.1:${api.port}${url}`)).status, 401);
  const image = await fetch(`http://127.0.0.1:${api.port}${url}`, { headers: { Authorization: `Bearer ${token}` } });
  assert.equal(image.status, 200);
  assert.equal(image.headers.get("content-type"), "image/png");
  assert.deepEqual(Buffer.from(await image.arrayBuffer()), png);
  const note = await fetch(`${api.base}/notes`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ title: "图片笔记", content: `![图](${url})` }) });
  assert.equal(note.status, 201);
  const noteId = (await note.json()).id;
  const future = new Date(Date.now() + 25 * 3600 * 1000);
  await cleanupAssets(api.client, future, directory);
  assert.equal((await api.client.query("SELECT count(*)::int AS count FROM media_assets WHERE id=$1", [id])).rows[0].count, 1);
  const remove = await fetch(`${api.base}/notes/${noteId}`, { method: "DELETE", headers: { Authorization: `Bearer ${token}` } });
  assert.equal(remove.status, 200);
  await cleanupAssets(api.client, future, directory);
  assert.equal((await api.client.query("SELECT count(*)::int AS count FROM media_assets WHERE id=$1", [id])).rows[0].count, 1);
  const purge = await fetch(`${api.base}/settings/recycle-bin/note/${noteId}/purge`, { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ confirmTitle: "图片笔记" }) });
  assert.equal(purge.status, 200);
  await cleanupAssets(api.client, future, directory);
  assert.equal((await api.client.query("SELECT count(*)::int AS count FROM media_assets WHERE id=$1", [id])).rows[0].count, 0);
  await assert.rejects(fs.stat(path.join(directory, id)), { code: "ENOENT" });
});
